/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bean.Animal;
import Bean.Cliente;
import Bean.Servico;
import Bean.TipoServico;
import Controller.AnimalController;
import Controller.ClienteController;
import Controller.ServicoController;
import Controller.TipoServicoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jocsa
 */
public class AdicionarServico extends javax.swing.JFrame {

    //LISTAS TEM DE SER CRIADAS FORA, PARA SER CONSUMIDA SEMPRE QUE PRECISAR DEPOIS NOS METODOS.
    private List<TipoServico> listaServico;
    private List<Cliente> listaCliente;
    private List<Animal> listaAnimal;
    private ServicoVIEW servicoView;
    
    //VARIAVEL CRIADA PARA NÃO FAZER A LEITURA DA LISTA NOVAMENTE
    private boolean verificadorListaServico = false;
    private boolean verificadorListaCliente = false;

    //ESSE CONSTRUTOR NÃO ESTÁ SERVINDO ESTÁ SENDO USADO NO MOMENTO, MAS DEIXEI POR SEGURANÇA.
    public AdicionarServico() {
        initComponents();
        this.setarServicoNoCombo();
        this.setarClienteNoCombo();
        int idDono = this.setarClienteNoCombo();
        this.setarAnimais(idDono);
    }

    public AdicionarServico(List<Cliente> listaCliente, ServicoVIEW servicoView ) {
        initComponents();
        this.listaCliente = listaCliente;
        this.setarServicoNoCombo();
        
        int idDono = this.setarClienteNoCombo();
        this.setarAnimais(idDono);
        this.servicoView = servicoView;
    }

    public void setarServicoNoCombo() {

        if (this.verificadorListaServico == false) {
            TipoServicoController tsc = new TipoServicoController();
            //PASSA A REFERENCIA NA MEMORIA DO COMBOBOX SERVICO E ADD O NOME NO PRÓPRIO TIPOSERVIÇODAO NA LEITURA NO BANCO.
            this.listaServico = tsc.listar(this.servico);
            this.verificadorListaServico = true;
        }

        TipoServico servicoSelecionado = this.listaServico.get(this.servico.getSelectedIndex());
        preco.setText(String.valueOf(servicoSelecionado.getValor()));

    }

    public int setarClienteNoCombo() {
        Cliente cliente = null;
        if (this.verificadorListaCliente == false) {
            ClienteController cc = new ClienteController();
            //PASSA A REFERENCIA NA MEMORIA DO COMBOBOX SERVICO E ADD O NOME NO PRÓPRIO TIPOSERVIÇODAO NA LEITURA NO BANCO.
            this.listaCliente = cc.listar(this.cliente);
            
            this.verificadorListaCliente = true;
            
            cliente = this.listaCliente.get(this.cliente.getSelectedIndex());

        } else {
            cliente = this.listaCliente.get(this.cliente.getSelectedIndex());
            this.setarAnimais(cliente.getId());
        }
        return cliente.getId();

    }

    //SETAR OS ANIMAIS DE ACORDO COM O CLIENTE
    public void setarAnimais(int idDono) {
        this.listaAnimal = null;
        AnimalController ac = new AnimalController();
        //PASSA A REFERENCIA NA MEMORIA DO COMBOBOX SERVICO E ADD O NOME NO PRÓPRIO TIPOSERVIÇODAO NA LEITURA NO BANCO.
        //BUSCA DE ACORDO COM O DONO
        this.listaAnimal = ac.listar(idDono);

        String[] animais = new String[this.listaAnimal.size()];
        int cont = 0;
//        animais[0] = "Escolha o animal!";
        for (Animal animal : this.listaAnimal) {
            animais[cont++] = animal.getNome();
        }

        this.animal.setModel(new javax.swing.DefaultComboBoxModel(animais));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        cliente = new javax.swing.JComboBox();
        animal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        custo = new javax.swing.JComboBox();
        servico = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        horario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Preço");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Animal");

        limpar.setText("LIMPAR");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        cliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um cliente" }));
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        animal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um cliente acima" }));
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Horário");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Serviço");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Gasto");

        preco.setEditable(false);

        custo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "70%", "50%", "35%", "25%" }));
        custo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoActionPerformed(evt);
            }
        });

        servico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um serviço" }));
        servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(limpar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(horario))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(animal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(servico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar)
                    .addComponent(limpar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(516, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed

        data.setText("");

    }//GEN-LAST:event_limparActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        AnimalController ac = new AnimalController();
        ServicoController sc = new ServicoController();
        ClienteController cc = new ClienteController();
        
        Animal animal = this.listaAnimal.get(this.animal.getSelectedIndex());
        TipoServico servico = this.listaServico.get(this.servico.getSelectedIndex());
        
        Servico s = new Servico();
        
        s.setData(data.getText());
        s.setHorario(horario.getText());
        
        char[] custoE = null;
        for (int i = 0; i < custo.getSelectedItem().toString().length(); i++) {
                custoE = custo.getSelectedItem().toString().toCharArray();
        }
        String custoC = "";
        for (int i = 0; i < 2; i++) {
            custoC += custoE[i]; 
        }
        
        float custoCorreto = (Float.parseFloat(preco.getText()) / 100) * Float.parseFloat(custoC);
        
        s.setCusto(custoCorreto);
        s.setPrecoServico(Float.parseFloat(preco.getText()));
        s.setId_animal(animal.getId());
        s.setNomeAnimal(animal.getNome());
        Cliente dono = cc.buscarUm(animal.getIdDono());
        s.setNomeDonoAnimal(dono.getNome());
        s.setId_tipoServico(servico.getId_servico());
        s.setNomeServico(servico.getNome());
        s.setFinalizado(false);
        sc.inserir(s);
        

        //IMPLEMENTAR ACIMA     IMPLEMENTAR ACIMA       IMPLEMENTAR ACIMA       IMPLEMENTAR ACIMA       IMPLEMENTAR ACIMA
        JOptionPane.showMessageDialog(null, "Serviço cadastrado com sucesso!");
        int dec = JOptionPane.showConfirmDialog(null, "Deseja adicionar outro serviço?");
        if (dec == 0) {

            data.setText("");

        } else {
            this.setVisible(false);
        }
        this.servicoView.listarTabela();
    }//GEN-LAST:event_cadastrarActionPerformed
   
    private void custoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custoActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        this.setarClienteNoCombo();
    }//GEN-LAST:event_clienteActionPerformed

    private void servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicoActionPerformed
        this.setarServicoNoCombo();
    }//GEN-LAST:event_servicoActionPerformed

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox animal;
    private javax.swing.JButton cadastrar;
    private javax.swing.JComboBox cliente;
    private javax.swing.JComboBox custo;
    private javax.swing.JTextField data;
    private javax.swing.JTextField horario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField preco;
    private javax.swing.JComboBox servico;
    // End of variables declaration//GEN-END:variables
}
